export const LOAD_TICKERS = 'LOAD_TICKERS';
export const SAVE_TO_INTERESTING = 'SAVE_TO_INTERESTING';
export const REMOVE_FROM_INTERESTING = 'REMOVE_FROM_INTERESTING';
export const SEARCH_TICKER = 'SEARCH_TICKER';
